### ISSUE TITLE
Dont get an email

### ISSUE THREAD

**Issue by neomib** [paulmillr/ostio-api#10]
Hi so i played a little with ost.io which is realy cool by the way..but i didn't get any email when i added a post to one of the topics...
What am i missing?

**Comment by andy5995** [comment]
@neomib I think you'll only get a notification email if someone posts on a forum you admin, or if someone replies to one of your posts.

If you post, no notification email is sent because the software assumes you don't need a notification, since you are the one who posted.

What's the link you posted at?

**Comment by neomib** [comment]
I added comments manually in [http://ost.io/@neomib/mobile](http://ost.io/@neomib/mobile) and tried to make some request with Postman just to see the result.
It makes sense though that it would not send an email if  i added posts to my own repository.
Thanks :)

**Comment by andy5995** [comment]
Yw. I replied to one of your posts.

**Comment by neomib** [comment]
Cool. Still no email :(

**Comment by andy5995** [comment]
Hmm.. try on mine? http://ost.io/@andy5995/blitzed-irc-trivia

**Comment by neomib** [comment]
Added a post...

**Comment by andy5995** [comment]
I didn't receive an email either. @paulmillr any ideas?
